### ISSUE TITLE
will tracer support serial communication?

### ISSUE THREAD

**Issue by JacksonK9** [agilexrobotics/tracer_ros#1]
will tracer support serial communication?

when I changed port to /dev/ttyUSB0, Program said that, Not Supported Yet!

Is there some plan to support serial?

If it is, when will be released?

thanks for your help!

**Comment by agilexrobotics** [comment]
Hello! I am very sorry for replying you so late. Tracer's serial SDK is not support yet now. Please pay attention to GitHub, and we will update it in the future！


------------------------------------------------------------------
发件人：k9632441 <notifications@github.com>
发送时间：2020年9月21日(星期一) 10:30
收件人：agilexrobotics/tracer_ros <tracer_ros@noreply.github.com>
抄　送：Subscribed <subscribed@noreply.github.com>
主　题：[agilexrobotics/tracer_ros] will tracer support serial communication? (#1)

will tracer support serial communication?
when I changed port to /dev/ttyUSB0, Program said that, Not Supported Yet!
Is there some plan to support serial?
If it is, when will be released?
thanks for your help!
