### ISSUE TITLE
Failed to send CAN frame

### ISSUE THREAD

**Issue by autonomousTurtle** [agilexrobotics/tracer_ros#5]
Hello! 

I am working to set up my tracer robot with an Nvidia Jetson Orin AGX development kit. 

I currently have the tracer CAN wired through the [Waveshare SN65HVD230 CAN Board](https://www.amazon.com/SN65HVD230-CAN-Board-Communication-Development/dp/B00KM6XMXO?th=1) as [recommended by NVIDIA](https://docs.nvidia.com/jetson/archives/r34.1/DeveloperGuide/text/HR/ControllerAreaNetworkCan.html?highlight=can%20bus#important-features). 

I set up my can0 port using: 

1. `$ modprobe mttcan`

2. `$ ip link set can0 up type can bitrate 500000`

Then I start ros with the following commands from this repo: 

1. `$ roslaunch tracer_bringup tracer_robot_base.launch` 
and 
2. `$ roslaunch tracer_bringup tracer_teleop_keyboard.launch'

The result is the following: 
![image](https://user-images.githubusercontent.com/31008838/205514468-3f339cd3-f73f-4d57-a4bc-18747a4ca272.png)

This results in a "Failed to send CAN frame" over and over each time a command is published from teleop_keyboard

Do you have any suggestions for testing and debugging the CAN port interface? Thank you!

**Comment by agilexrobotics** [comment]
Hi Aaron
Nice to meet you, this is Nick.
have you make sure is there any CAN device in command : ifconfig -a,
if there have a can device, and then test the cammand : candump can#, the# is the number that you have wire to tracer.
Nick
Best Regards,
AGILEX ROBOTICS 
YouTube AgileX Robotics <https://www.youtube.com/channel/UCm4KH9QLZvkp02-23z3YbjQ > | Linkedin AgileX Robotics <https://www.linkedin.com/company/agilexrobotics/?viewAsMember=true > | www.agilex.ai <http://www.agilex.ai/ >
------------------------------------------------------------------
发件人：Aaron Crookes ***@***.***>
发送时间：2022年12月5日(星期一) 04:44
收件人：agilexrobotics/tracer_ros ***@***.***>
抄　送：Subscribed ***@***.***>
主　题：[agilexrobotics/tracer_ros] Failed to send CAN frame (Issue #5)
Hello!
I am working to set up my tracer robot with an Nvidia Jetson Orin AGX development kit.
I currently have the tracer CAN wired through the Waveshare SN65HVD230 CAN Board <https://www.amazon.com/SN65HVD230-CAN-Board-Communication-Development/dp/B00KM6XMXO?th=1 > as recommended by NVIDIA <https://docs.nvidia.com/jetson/archives/r34.1/DeveloperGuide/text/HR/ControllerAreaNetworkCan.html?highlight=can%20bus#important-features >.
I set up my can0 port using:

 * 
$ modprobe mttcan

 * 
$ ip link set can0 up type can bitrate 500000
Then I start ros with the following commands from this repo:

 * 
$ roslaunch tracer_bringup tracer_robot_base.launch
 and

 * 
`$ roslaunch tracer_bringup tracer_teleop_keyboard.launch'
The result is the following:
 <https://user-images.githubusercontent.com/31008838/205514468-3f339cd3-f73f-4d57-a4bc-18747a4ca272.png >
This results in a "Failed to send CAN frame" over and over each time a command is published from teleop_keyboard
Do you have any suggestions for testing and debugging the CAN port interface? Thank you!
